---

- name: set mariadb gpg
  apt_key: id=1BB943DB url="http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xcbcb082a1bb943db" state=present
  when: ansible_distribution_release == 'wheezy'

- name: add mariadb apt sources
  apt_repository: repo='deb http://mirror.netinch.com/pub/mariadb/repo/10.0/debian wheezy main'
  when: ansible_distribution_release == 'wheezy'

- name: Install mariaDB
  apt: pkg=mariadb-server state=present
  notify: mysql_secure_installation

- meta: flush_handlers

- name: Copy .my.cnf file with root password credentials
  template: src=root.my.cnf dest=/root/.my.cnf owner=root mode=600

- name: Copy MariaDB config
  template: src=my.cnf dest=/etc/mysql/my.cnf backup=yes
  notify: Restart MariaDB

- name: Ensure that python-mysqldb is installed
  apt: pkg=python-mysqldb state=present

- name: Create database folder
  file: dest=/var/backups/mysql state=directory

- name: Copy backup script to server
  template: src=mysql_dump_all_single.j2 dest=/sbin/mysql_dump_all_single.sh mode=0755

- name: Set backup script to crontab
  cron: name="Take snapshot" minute="0" hour="*/4" job='/sbin/mysql_dump_all_single.sh' state=present user=root

- meta: flush_handlers
