---
- hosts: magento

  vars:
    stackid: magento
    vagrant: true
  become: yes

  roles:
    - role: common
    - role: ssmtp
    - role: mariadb
      tags: [ 'mariadb' ]
    - role: nginx
      tags: [ 'nginx' ]
    - role: php7
      tags: [ 'php' ]
    - role: redis
      tags: [ 'redis' ]
    - role: base
      tags: [ 'base' ]
    - role: site
      site_name: 'development'
      site: '{{ site_defaults | combine(development.site, recursive=True) }}'
    - role: magerun
# Installing magento halted for testing
#    - role: magento
#      site_name: 'development'
#      site: '{{ site_defaults | combine(development.site, recursive=True) }}'
#      tags: [ 'magento' ]
    - role: rsync
      remote: 'user@example.com'
      path: '/srv/staging/'