---
- hosts: wordpress

  vars:
    stackid: wordpress
    vagrant: true
  become: yes

  roles:
    - role: common
    - role: ssmtp
    - role: mariadb
      tags: [ 'mariadb' ]
    - role: nginx
      tags: [ 'nginx' ]
    - role: php7
      tags: [ 'php' ]
    - role: base
      tags: [ 'base' ]
    - role: site
      site_name: 'development'
      site: '{{ site_defaults | combine(development.site, recursive=True) }}'
    - role: wp-cli
    - role: wordpress
      site_name: 'development'
      site: '{{ site_defaults | combine(development.site, recursive=True) }}'
      tags: [ 'wordpress' ]
